### ISSUE TITLE
feat: support constants

### ISSUE THREAD

**Issue by ghostsquad** [sh0rez/docsonnet#10]
It is useful to support constants in libraries like (in fact doc-utils does this)

```jsonnet
{  
   colors: {
     '#green': d.const("the color green")
     green: "green"
   }
}
```

As such, I'd like to be able to document these constants. Possible look for this:

---

### Constants

* `colors.green` `(string)` : `"green"` - the color green

**Comment by sh0rez** [comment]
Given in Jsonnet everything is immutable unless overwritten using a patch, `const` seems a bit too much.

Instead, I suggest having `d.val` (`d.value.new`), which allows to document regular fields, which would be included in a special "Fields" category:

### Fields
* `colors.green` (`string`): `"green"` - the color green

Question would be whether to have these "top level", or nested within their respective `obj` keys

**Comment by ghostsquad** [comment]
Yep, you are right that fields is a better term.

I think they should be nested. It's a natural extension of the "object" being a namespace.
