### ISSUE TITLE
feat: support new style of jsonnet bundler import (full path)

### ISSUE THREAD

**Issue by ghostsquad** [sh0rez/docsonnet#4]
I noticed that this doesn't work:

```
local d = import "github.com/sh0rez/docsonnet/doc-util";
```

but this does:

```
local d = import 'doc-util/main.libsonnet';
```

**Comment by sh0rez** [comment]
Definitely!

The static importer needs to be extended to handle this as well: 
https://github.com/sh0rez/docsonnet/blob/4c6f532e05dba116b025966364fc7a2f75e47b1e/pkg/docsonnet/load.go#L93-L99
